@rootUrl = http://localhost:8000/api/v1
@userApi = {{rootUrl}}/users
@productApi = {{rootUrl}}/products
@catApi = {{rootUrl}}/categories
@orderApi = {{rootUrl}}/orders

# ======== user API
###Register user
POST {{userApi}}
Content-Type: application/json

{
    "fName": "Gaurav",
    "lName": "Shreenet",
    "email": "a@a.com",
    "phone": "0451352524",
    "address": "32 Brittain Crescent, Hillsdale NSW",
    "password": "aA1234"
}

###login user
POST {{userApi}}/sign-in
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "aA1234"
}

###get user profile
GET {{userApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDgyMjExMzEsImV4cCI6MTcwODIyMTE5MX0.VZT5BBLcenLAeGu9edfL_r7IcsjX6YtJD0dhY8HDnqI

###get access-jwt
GET {{userApi}}/get-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDgyMjExMzEsImV4cCI6MTcxMDgxMzEzMX0.Msg2nWNQYdVSBIsaMLSSR4jhopjafd4gXZvojltHTnI

###request otp
POST {{userApi}}/request-otp
Content-Type: application/json

{
    "email": "a@a.com"
}

###Update user profile
PATCH {{userApi}}/user-profile
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU2NDEzMTksImV4cCI6MTcwNTY0MjIxOX0.UllvZTihG3fB7wEIWInIttytuktICNqPsP21ks43WcM
Content-Type: application/json

{
    "_id": "65a47133ebc597c33989c325",
    "fName": "Gaurav",
    "lName": "Shreenet",
    "phone": "0451352524",
    "address": "32 Brittain Crescent, Hillsdale NSW"
}


# ============== products
### all products
GET {{productApi}}

### all products
GET {{productApi}}/nike-airmax


### new arrival products
GET {{productApi}}/new-arrival


# ========= categories

###Categories
GET {{catApi}}/women-shoes


# =============== user Order

###get user orders
GET {{orderApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MDkzNDg0NDYsImV4cCI6MTcwOTM0OTM0Nn0.8jA1xOB_7F3gDmUd5zaJZMAqbzMs_lW2_S61E5wTh2k